### ISSUE TITLE
ERR_OSSL_DSO_COULD_NOT_LOAD_THE_SHARED_LIBRARY

### ISSUE THREAD

**Issue by decoderid** [rollivier/adonis5-firebase-admin#2]
just install this package, but got error

```
    err: {
      "type": "Error",
      "message": "error:25078067:DSO support routines:win32_load:could not load the shared library",
      "stack":
          Error: error:25078067:DSO support routines:win32_load:could not load the shared library
              at Sign.sign (internal/crypto/sig.js:110:29)
              at Object.sign (E:\adonis\node_modules\jwa\index.js:152:45)
              at Object.jwsSign [as sign] (E:\adonis\node_modules\jws\lib\sign-stream.js:32:24)
              at Object.module.exports [as sign] (E:\adonis\node_modules\jsonwebtoken\sign.js:204:16)
              at ServiceAccountCredential.createAuthJwt_ (E:\adonis\node_modules\firebase-admin\lib\credential\credential-internal.js:102:20)
              at ServiceAccountCredential.getAccessToken (E:\adonis\node_modules\firebase-admin\lib\credential\credential-internal.js:75:26)
              at FirebaseAppInternals.refreshToken (E:\adonis\node_modules\firebase-admin\lib\firebase-app.js:46:49)
              at FirebaseAppInternals.getToken (E:\adonis\node_modules\firebase-admin\lib\firebase-app.js:37:25)
              at AuthorizedHttpClient.getToken (E:\adonis\node_modules\firebase-admin\lib\utils\api-request.js:679:34)
              at AuthorizedHttpClient.send (E:\adonis\node_modules\firebase-admin\lib\utils\api-request.js:667:21)
      "opensslErrorStack": [
        "error:0E076071:configuration file routines:module_run:unknown module name",
        "error:0E07506E:configuration file routines:module_load_dso:error loading dso",
        "error:25070067:DSO support routines:DSO_load:could not load the shared library"
      ],
      "library": "DSO support routines",
      "function": "win32_load",
      "reason": "could not load the shared library",
      "code": "ERR_OSSL_DSO_COULD_NOT_LOAD_THE_SHARED_LIBRARY",
      "status": 500
    }
```

**Comment by decoderid** [comment]
need to install openssl 32bit
